const { cmd } = require("../command");
const yts = require("yt-search");
const { ytmp3 } = require("@vreden/youtube_scraper");
const axios = require("axios");

cmd(
  {
    pattern: "song",
    react: "🎵",
    desc: "Download Song from YouTube",
    category: "download",
    filename: __filename,
  },
  async (robin, mek, m, { from, q, quoted, reply }) => {
    try {
      if (!q) return reply("*සින්දුවේ නම හෝ YouTube ලින්ක් එකක් දෙන්න.* 🎧");

      await reply("🔍 සෙවීම ආරම්භ වුණා...");

      // Search YouTube for the video
      const search = await yts(q);
      const video = search.videos[0];

      if (!video || !video.videoId)
        return reply("❌ වීඩියෝවක් හමු නොවුණා.");

      const videoUrl = `https://youtu.be/${video.videoId}`;

      await reply(`📥 Download link prepare කරමින්: ${videoUrl}`);

      // Attempt to get MP3 download info
      const song = await ytmp3(videoUrl, "mp3");

      if (!song || !song.download || !song.download.url) {
        return reply("❌ සින්දුව බාගත කිරීමට නොහැක. වෙනත් ලින්ක් එකක් උත්සාහ කරන්න.");
      }

      await reply("⬇️ බාගත වෙමින්...");

      const res = await axios.get(song.download.url, { responseType: "arraybuffer" });
      const audioBuffer = Buffer.from(res.data);
      const fileSizeMB = (audioBuffer.length / (1024 * 1024)).toFixed(2);

      // Send thumbnail with details
      const caption = `
🎶 *Title:* ${video.title}
⏱️ *Duration:* ${video.timestamp}
👁️ *Views:* ${video.views}
🔗 *Link:* https://youtu.be/${video.videoId}
📦 *Size:* ${fileSizeMB} MB

_🔥 Generated by MR SENAL_
`;

      await robin.sendMessage(
        from,
        { image: { url: video.thumbnail }, caption },
        { quoted: mek }
      );

      await reply("📤 අප්ලෝඩ් වෙමින්...");

      // Send MP3 as audio
      await robin.sendMessage(
        from,
        {
          audio: audioBuffer,
          mimetype: "audio/mpeg",
          ptt: false,
          fileName: `${video.title}.mp3`,
        },
        { quoted: mek }
      );

      // Optional: also send as document
      await robin.sendMessage(
        from,
        {
          document: audioBuffer,
          mimetype: "audio/mpeg",
          fileName: `${video.title}.mp3`,
          caption: "📦 MP3 as Document",
        },
        { quoted: mek }
      );

      await reply("✅ සාර්ථකව අවසන්! 🎧");

    } catch (e) {
      console.error("❌ Error in .song:", e);
      reply(`❌ දෝෂයක්: ${e.message}`);
    }
  }
);
