const { cmd } = require("../command");
const {
  ytmp3,
  search,
  playmp3,
} = require("@kelvdra/scraper");

cmd(
  {
    pattern: "play",
    react: "🎧",
    desc: "Download YouTube Music Audio",
    category: "download",
    filename: __filename,
  },
  async (robin, mek, m, { from, q, reply }) => {
    try {
      if (!q) return reply("*🔍 නමක් හරි ලින්ක් එකක් හරි දෙන්න*");

      let result, video;

      if (typeof playmp3 === "function") {
        // ✅ Use playmp3 if available
        result = await playmp3(q);
        video = {
          title: result.title,
          duration: result.duration,
          views: result.views,
          published: result.published,
          url: result.url,
          thumbnail: result.thumbnail,
        };
      } else {
        // 🔁 Fallback to search + ytmp3
        const results = await search(q);
        video = results[0];
        if (!video) return reply("❌ ගීතය හමු නොවීය.");

        result = await ytmp3(video.url, "mp3");
        result.title = video.title;
        result.duration = video.duration;
        result.views = video.views;
        result.published = video.published;
        result.thumbnail = video.thumbnail;
        result.url = video.url;
      }

      if (!result.download) {
        return reply("❌ Download link එක ලබා ගත නොහැක.");
      }

      const caption = `
🎧 *SENAL MD Song Downloader*

🎶 *Title:* ${result.title}
⏱️ *Duration:* ${result.duration}
👁️ *Views:* ${result.views}
📤 *Uploaded:* ${result.published}
🔗 *URL:* ${result.url}

🔊 *Type:* Audio (.mp3)

╰───────⭓
🌟 Generated by: *Mr Senal*
`;

      // 🖼 Thumbnail with metadata
      await robin.sendMessage(
        from,
        {
          image: { url: result.thumbnail },
          caption,
        },
        { quoted: mek }
      );

      // 🎧 Audio streaming
      await robin.sendMessage(
        from,
        {
          audio: { url: result.download },
          mimetype: "audio/mpeg",
          fileName: `${result.title}.mp3`,
        },
        { quoted: mek }
      );

      return reply("✅ *Song sent successfully!*");
    } catch (e) {
      console.error("Play Error:", e);
      return reply(`❌ Error: ${e.message}`);
    }
  }
);
