const { cmd } = require("../command");
const { playmp3 } = require("@kelvdra/scraper");

cmd(
  {
    pattern: "play",
    react: "🎧",
    desc: "Download YouTube Music Audio",
    category: "download",
    filename: __filename,
  },
  async (robin, mek, m, { from, q, reply }) => {
    try {
      if (!q) return reply("*🔍 නමක් හරි ලින්ක් එකක් හරි දෙන්න*");

      const result = await playmp3(q);
      if (!result || !result.download) {
        return reply("❌ ගීතය හමු නොවීය. වෙනත් වචනයක් උත්සාහ කරන්න.");
      }

      const caption = `
🎧 *SENAL MD Song Downloader*

🎶 *Title:* ${result.title}
⏱️ *Duration:* ${result.duration}
👁️ *Views:* ${result.views}
📤 *Uploaded:* ${result.published}
🔗 *URL:* ${result.url}

🔊 *Type:* Audio (.mp3)

╰───────⭓
🌟 Generated by: *Mr Senal*
`;

      await robin.sendMessage(
        from,
        {
          image: { url: result.thumbnail },
          caption,
        },
        { quoted: mek }
      );

      await robin.sendMessage(
        from,
        {
          audio: { url: result.download },
          mimetype: "audio/mpeg",
          fileName: `${result.title}.mp3`,
        },
        { quoted: mek }
      );

      return reply("✅ *Song sent successfully!*");
    } catch (e) {
      console.error("Play Error:", e);
      return reply(`❌ Error: ${e.message}`);
    }
  }
);
